from ..shared.solver import Solver
from ..shared.fibonacci import fibonacci
from ..shared.more_itertools import filter, take, take_while

description = '''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

def _solve(print = print):
    limit = 4000000
    total = sum(take_while(lambda n: n < limit, fibonacci()))
    print(f'Total: {total}')
    return True


solver = Solver(2,
                'Even Fibonacci numbers',
                description,
                _solve
                )
